#!/bin/bash

APPNAME=$1
PACKAGE=$2

if [ -z "$APPNAME" ] || [ -z "$PACKAGE" ]; then
  echo "Uso: ./android-init NomeApp com.exemplo.app"
  exit 1
fi

PKG_PATH=$(echo $PACKAGE | tr '.' '/')

mkdir -p $APPNAME/src/$PKG_PATH/{core,android}
mkdir -p $APPNAME/{res/drawable,assets,libs}

cat > $APPNAME/AndroidManifest.xml <<EOF
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="$PACKAGE"
    android:versionCode="1"
    android:versionName="1.0">
    <uses-sdk
        android:minSdkVersion="31"
        android:targetSdkVersion="31"/>
    <application
        android:label="$APPNAME"
        android:theme="@android:style/Theme.Material.Light.NoActionBar">
        <activity android:name=".android.MainActivity"
                 android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
    </application>
</manifest>
EOF

cat > $APPNAME/src/$PKG_PATH/core/AppCore.java <<EOF
package $PACKAGE.core;

public class AppCore {

    private int counter = 0;

    public String click() {
        counter++;
        return "Cliques: " + counter;
    }
}
EOF

cat > $APPNAME/src/$PKG_PATH/android/MainActivity.java <<EOF
package $PACKAGE.android;

import android.app.Activity;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.TextView;

import $PACKAGE.core.AppCore;

public class MainActivity extends Activity {

    private AppCore core = new AppCore();

    @Override
    protected void onCreate(Bundle b) {
        super.onCreate(b);

        LinearLayout layout = new LinearLayout(this);
        layout.setOrientation(LinearLayout.VERTICAL);
        layout.setGravity(Gravity.CENTER);

        TextView tv = new TextView(this);
        tv.setText("Cliques: 0");

        Button bt = new Button(this);
        bt.setText("Clicar");

        bt.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                tv.setText(core.click());
            }
        });

        layout.addView(tv);
        layout.addView(bt);

        setContentView(layout);
    }
}
EOF

echo "Projeto $APPNAME criado com core multiplataforma"
