#!/bin/bash
set -e

read -p "nome do apk: " FILE

if [ -z "$FILE" ]; then
  echo "Uso: ./android-builds NomeDoApp"
  exit 1
fi

ANDROID_JAR=$ANDROID_HOME/platforms/android-31/android.jar

BUILD=build
AAPT=$BUILD/aapt
CLASSES=$BUILD/classes
DEX=$BUILD/dex
APK=$BUILD/apk

echo "__clear_build__"
rm -rf $BUILD
mkdir -p $AAPT $CLASSES $DEX $APK

echo "__aapt2_Compila__"
aapt2 compile --dir res -o $AAPT/resources.zip

echo "__gerando_link e R.java__"
aapt2 link -I $ANDROID_JAR --manifest AndroidManifest.xml --java $BUILD -o $AAPT/link.apk $AAPT/resources.zip --auto-add-overlay

echo "__compilado_java__"
javac  -source 8 -target 8  -bootclasspath $ANDROID_JAR -d $CLASSES $(find src -name "*.java") $(find $BUILD -name "R.java")

#echo "__empacotando_tudo__"
#cd $CLASSES
#zip -r classes.zip .
#cd ..

echo "__criando_classes.dex__"
d8 --min-api 31 --output $DEX $(find $CLASSES -name "*.class")

echo "__insertiro_classes.zip_no_apk__"
zip -j $AAPT/link.apk $DEX/classes.dex

echo "__zipaling__"
zipalign -f 4 $AAPT/link.apk $APK/$FILE.apk

 ##sera usando quando nao tiver file debug.keystore##
if [ ! -f ~/.android/debug.keystore ]; then
   echo "__criando_chave_debug__"
 keytool -genkeypair -keystore ~/.android/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=BR"
fi

echo "__assinando_apk__"
apksigner sign --ks ~/.android/debug.keystore --ks-pass pass:android $APK/$FILE.apk

echo
echo "APK gerado: $APK/$FILE.apk"
